// COMPILED SCRIPTS

// Original file: _FJ.js
var FJ=FJ||{};FJ.NOTIF_EVENT="fjEvent",FJ.NOTIF_NAVIGATION="fjNavigation",FJ.MSG_NAVIGATE="fjNavigate",FJ.MSG_NAVIGATE_UNDO="fjNavigateUndo",FJ.MSG_NAVIGATE_REDO="fjNavigateRedo";
// Original file: Application.js
FJ.Application=new function(){var e=this,t=[];this.model={},this.slug="",this.init=function(t){FJ.Router.init(),FJ.Router.start(t),e.broadcast(FJ.Router.navigateBySlug)},this.createMediator=function(e){e=e||"mediator"+t.length;var n=new FJ.Mediator(e,this);return t.push(n),n},this.destroyMediator=function(e){var n=t.indexOf(e);if(n<0)return;t.splice(n,1)},this.registerViews=function(){for(var e=0,t=arguments.length;e<t;e++){arguments[e].register();var n=arguments[e].onRegister;n&&n()}},this.broadcast=function(e){var n=t.length;for(var r=0;r<n;r++)t[r].notify(e)}};
// Original file: Define.js
FJ.define=function(e,t,n,r){e[t]=function(e){if(e==undefined)return n();r&&r(e)}};
// Original file: ElementWrapper.js
FJ.ElementWrapper=function(e){var t=this;e&&(t.div=e),FJ.define(this,"id",function(){return t.div.id},function(e){t.div.id=e}),FJ.define(this,"class",function(){return t.div.className},function(e){t.div.className=e}),this.setDisplay=function(e){t.div.style.display=e},this.opacity=function(e){t.div.style.opacity=e},this.registerClick=function(e){t.div.addEventListener("click",e)},this.unRegisterClick=function(e){t.div.addEventListener("click",e)},this.width=function(){return t.div.offsetWidth},this.height=function(){return t.div.offsetHeight},this.mouseEnabled=function(e){t.div.style["pointer-events"]=e?"auto":"none"}};
// Original file: EventDispatcher.js
FJ.EventDispatcher=function(e){"use strict";var t=[];this.addEventListener=function(n){if(t.indexOf(n)>-1)return;t.push(n),e&&e(t.length)},this.removeEventListener=function(n){var r=t.indexOf(n);return r<0?null:(e&&e(t.length-1),t.splice(r,1))},this.dispatch=function(e){var n=t.length;for(var r=0;r<n;r++)t[r](e)}};
// Original file: Extensions.js
(function(e,t){var n="",r,i,s;e.addEventListener?(r="addEventListener",i="removeEventListener"):(r="attachEvent",i="detachEvent",n="on"),t.onmousewheel!==undefined&&(s="mousewheel");try{WheelEvent("wheel"),s="wheel"}catch(o){}s||(s="DOMMouseScroll"),e.addWheelListener=function(e,t,i){var o=s=="wheel"?t:u(t);return e[r](n+s,o,i||!1),s=="DOMMouseScroll"&&e[r]("MozMousePixelScroll",o,i||!1),o},e.removeWheelListener=function(e,t){e[i](n+s,t),s=="DOMMouseScroll"&&e[i]("MozMousePixelScroll",t)};var u=function(t){return function(n){!n&&(n=e.event);var r={originalEvent:n,target:n.target||n.srcElement,type:"wheel",deltaMode:n.type=="MozMousePixelScroll"?0:1,deltaX:0,deltaY:0,preventDefault:function(){n.preventDefault?n.preventDefault():n.returnValue=!1}};return s=="mousewheel"?(r.deltaY=-n.wheelDelta/10,n.wheelDeltaX&&(r.deltaX=-n.wheelDeltaX/10)):r.deltaY=n.detail,r.deltaX=r.deltaX|0,r.deltaY=r.deltaY|0,t(r)}}})(window,document),function(){var e=0,t=["ms","moz","webkit","o"];for(var n=0;n<t.length&&!window.requestAnimationFrame;++n)window.requestAnimationFrame=window[t[n]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[t[n]+"CancelAnimationFrame"]||window[t[n]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(t,n){var r=(new Date).getTime(),i=Math.max(0,16-(r-e)),s=window.setTimeout(function(){t(r+i)},i);return e=r+i,s}),window.cancelAnimationFrame||(window.cancelAnimationFrame=function(e){clearTimeout(e)})}(),Array.prototype.indexOf||(Array.prototype.indexOf=function(e,t){for(var n=t||0,r=this.length;n<r;n++)if(this[n]===e)return n;return-1}),(!window.console||!console.log)&&function(){var e=function(){},t=["assert","clear","count","debug","dir","dirxml","error","exception","group","groupCollapsed","groupEnd","info","log","markTimeline","profile","profileEnd","markTimeline","table","time","timeEnd","timeStamp","trace","warn"],n=t.length,r=window.console={};while(n--)r[t[n]]=e}();
// Original file: Loader.js
var FJ=FJ||{};FJ.Loader=FJ||{},FJ.Loader.loadJSON=function(e,t){var n=new XMLHttpRequest;n.open("GET",e),n.onreadystatechange=function(){n.readyState==4&&t(JSON.parse(n.responseText))},n.send()},window.__loadCount=0,FJ.Loader.loadJSONP=function(e,t){var n=document.createElement("script");t!=undefined&&(e+="&callback=__loaded"+window.__loadCount),n.src=e,document.body.appendChild(n),t!=undefined&&(window["__loaded"+window.__loadCount]=function(e){t(e)},window.__loadCount++)},FJ.Loader.loadPlainText=function(e,t){var n=new XMLHttpRequest;n.open("GET",e),n.onreadystatechange=function(){n.readyState==4&&t(n.responseText)},n.send()},FJ.Loader.loadScript=function(e,t){var n=document.createElement("script");n.onload=t,n.src=e,document.getElementsByTagName("head")[0].appendChild(n)},FJ.Loader.loadLink=function(e,t){var n=document.createElement("link");n.setAttribute("rel","stylesheet"),n.setAttribute("type","text/"+e.split(".")[1]),n.setAttribute("href",e),n.onload=t,document.getElementsByTagName("head")[0].appendChild(n)},FJ.Loader.loadFramework=function(e,t){var n=["behaviors/CSSTransitionBehavior.js","behaviors/CSSxFormBehavior.js","core/Application.js","core/EventDispatcher.js","core/Mediator.js","core/Notification.js","core/Router.js","util/display/DisplayUtil.js","util/viewport/ViewportUtil.js","util/Capabilities.js","util/Extensions.js","util/ImageDataUtil.js","util/Slug.js","util/modernizr.js","util/VirtualScroll.js","util/Define.js","view/Sprite.js","view/Template.js"];FJ.Loader.loadScript(e+"_FJ.js",function(){var r=n.length;for(var i=0;i<n.length;i++)FJ.Loader.loadScript(e+n[i],function(){r--,r==0&&t()})})};
// Original file: Mediator.js
FJ.Mediator=function(e){this.name=e,this.notify=function(e){this.update&&this.update(e)}};
// Original file: Notification.js
FJ.Notification=function(e,t,n){if(!e)throw"NOTIFICATION ERROR. Message cannot be null";if(t==FJ.NOTIF_NAVIGATION&&!n)throw"NOTIFICATION ERROR. Navigation type notifications require a slug";this.message=e,this.vars=null,this.type=t||FJ.NOTIF_EVENT,this.slug=n||"",this.action=null,this.postAction=null;var r=this;this.send=function(){FJ.Application.broadcast(r)}};
// Original file: Router.js
FJ.Router=new function(){"use strict";var e=this,t=" ",n=100,r=document.location.href,i=r.indexOf("#"),s=i>0?r.substring(0,i):r,o=function(){var e=r.indexOf("#"),n=r.substring(e+2);return e>0&&e!=r.length-1?n:t},u=function(e){FJ.Application.slug=e,r=s+"#/"+e,document.location.href=r};this.start=function(i){t=i,e.navigateBySlug=new FJ.Notification(FJ.MSG_NAVIGATE,FJ.NOTIF_NAVIGATION,o()),setInterval(function(){document.location.href!=r&&(r=document.location.href,e.navigateBySlug.slug=o(),FJ.Application.broadcast(e.navigateBySlug))},n)},this.init=function(){FJ.Application.createMediator("router").update=function(e){e.type==FJ.NOTIF_NAVIGATION&&u(e.slug)}}};
// Original file: Template.js
FJ.Template=function(templateString){this.execute=function(element,params){var ct=templateString.split("\n").join("");for(var p in params)if(typeof params[p]=="object"){var pattern=new RegExp("%for[(]"+p+"[)]%(.*?)%for%","g"),me=new RegExp("this","g"),match,matches=[];while((match=pattern.exec(ct))!==null)matches.push(match);for(var i=0;i<matches.length;i++){match=matches[i];var l=params[p],r="",c=match[1];for(var j=0;j<l.length;j++)r+=c.replace(me,""+p+"["+j+"]");ct=ct.replace(match[0],r)}}for(var p in params)if(typeof params[p]=="boolean"||typeof params[p]=="object"){var pattern=new RegExp("%if[(]"+p+"([.|[][^%]*)[)]%","g"),match,matches=[];while((match=pattern.exec(ct))!==null)matches.push(match);for(var i=0;i<matches.length;i++){match=matches[i];var code="params[p]"+match[1],res;try{res=eval(code),res=res==undefined||res==0?"false":"true"}catch(e){throw"TEMPLATE ERROR. Unable to call "+match[1]+" on '"+params[p]+"' ("+e+")"}ct=ct.replace(match[0],"%if("+res+")%")}pattern=new RegExp("%if[(]"+p+"[)]%","g"),matches=[];while((match=pattern.exec(ct))!==null)matches.push(match);for(var i=0;i<matches.length;i++)ct=ct.replace(matches[i][0],"%if("+params[p]+")%");var pattern=new RegExp("%if[(]true[)]%(.*?)%if%","g"),match,matches=[];while((match=pattern.exec(ct))!==null)matches.push(match);for(var i=0;i<matches.length;i++)ct=ct.replace(matches[i][0],matches[i][1]);var pattern=new RegExp("%if[(]false[)]%(.*?)%if%","g"),match,matches=[];while((match=pattern.exec(ct))!==null)matches.push(match);for(var i=0;i<matches.length;i++)ct=ct.replace(matches[i][0],"")}for(var p in params)if(typeof params[p]=="string"||typeof params[p]=="object"){var pattern=new RegExp("%"+p+"([.|[][^%]*)%","g"),match,matches=[];while((match=pattern.exec(ct))!==null)matches.push(match);for(var i=0;i<matches.length;i++){match=matches[i];var code="params[p]"+match[1],res;try{res=eval(code)}catch(e){throw"TEMPLATE ERROR. Unable to call "+match[1]+" on '"+params[p]+"' ("+e+")"}ct=ct.replace(match[0],res)}pattern=new RegExp("%"+p+"%","g"),matches=[];while((match=pattern.exec(ct))!==null)matches.push(match);for(var i=0;i<matches.length;i++)ct=ct.replace(matches[i][0],params[p])}element==document.body?document.body.insertAdjacentHTML("beforeend",ct):element.innerHTML=ct}};
